/**
 * Every HTTP path the web client is allowed to call, in one place.
 *
 * The API builds its controllers from these constants so a route rename is a
 * compile error rather than a 404 discovered at runtime.
 */
export const API_ROUTES = {
  health: {
    root: '/health',
    liveness: '/health/live',
    readiness: '/health/ready',
  },
  auth: {
    base: '/auth',
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    forgotPassword: '/auth/forgot-password',
    sessions: '/auth/sessions',
    resetPassword: '/auth/reset-password',
  },
  users: {
    base: '/users',
    profile: '/users/me',
    preferences: '/users/me/preferences',
  },
  conversations: {
    base: '/conversations',
    byId: (id: string) => `/conversations/${id}`,
    archive: (id: string) => `/conversations/${id}/archive`,
    restore: (id: string) => `/conversations/${id}/restore`,
    messages: (id: string) => `/conversations/${id}/messages`,
    message: (conversationId: string, messageId: string) =>
      `/conversations/${conversationId}/messages/${messageId}`,
  },
  ai: {
    base: '/ai',
    providers: '/ai/providers',
    agent: '/ai/agent',
    agentStream: '/ai/agent/stream',
    context: '/ai/context',
  },
  voice: {
    base: '/voice',
    transcribe: '/voice/transcribe',
    synthesize: '/voice/synthesize',
    voices: '/voice/voices',
  },
  analytics: {
    base: '/analytics',
    summary: '/analytics/summary',
    usage: '/analytics/usage',
    activity: '/analytics/activity',
  },
} as const;

/** Auth endpoints that must never carry an Authorization header. */
export const ANONYMOUS_ROUTES: readonly string[] = [
  API_ROUTES.auth.login,
  API_ROUTES.auth.register,
  API_ROUTES.auth.refresh,
  API_ROUTES.auth.forgotPassword,
  API_ROUTES.health.root,
  API_ROUTES.health.liveness,
  API_ROUTES.health.readiness,
];

/**
 * Client-side paths the API links to from an email.
 *
 * Lives here because an emailed link has to agree with the router: a reset URL
 * built from a path string in the API would silently drift from the route table.
 */
export const WEB_ROUTES = {
  resetPassword: '/reset-password',
} as const;

/** Storage key for the persisted (non-sensitive) auth session. */
export const AUTH_STORAGE_KEY = 'voiceflow.auth.session';

/** Storage key for the theme chosen before the user profile is loaded. */
export const THEME_STORAGE_KEY = 'voiceflow.theme';

/** Header carrying the correlation id generated by the client. */
export const REQUEST_ID_HEADER = 'x-request-id';

/** Header a client may set to request a specific API version. */
export const API_VERSION_HEADER = 'x-api-version';

/** Value pinned into `API_VERSION_HEADER` by the web client. */
export const API_VERSION = '1';
